### PR TITLE
Harmonic values patch

### PR DESCRIPTION
**Pull request by jvela018**

### CODE REVIEW

**Comment by jvela018** [comment]
I also corrected the potential length of the variable names (itemsize=500). 
Removed dummy Area variable

**Comment by jvela018** [comment]
Hi @raback ,

Long time no talk :D. Please approve this PR and merge to main. Thanks

/Jon

**Comment by jvela018** [comment]
@raback ,

Please approve to merge. Thanks

**Comment by raback** [comment]
Thanx Jon!

**Pull request merged**
